# Basic Information 
title: Yuan Zhang
position: Ph.D. Student
affiliation: Southeast University
affiliation_link: http://www.seu.edu.cn
affiliation_logo: 
email: yuanzhang_ (at) seu.edu.cn

# Search Engine Optimization (SEO)
keywords: Yuan Zhang
canonical: 
description: Yuan Zhang is a Ph.D. student at Southeast University. Her research focuses on medical image processing, histopathology image analysis, classification and image segmentation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=ikxbso8AAAAJ&hl=en&oi=ao
github_link: https://github.com/yuanzhang7/
linkedin: 
twitter: 

cv_pdf: ./assets/CV_Yuan_Zhang.pdf

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./html_source_file/assets/img/favicon.png
favicon_dark: ./html_source_file/assets/img/favicon-dark.png

# Footnotes
footnote: Thanks yaoyao-liu for his very exquisite template.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
